version: '3.8'
services:
  app:
    build: .
    container_name: mini-eshop
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=mini_eshop
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mini-eshop-mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


